gitfileviewerurl:
    https://github.com/openvswitch/ovs/blob/master/
gitrawfileviewerurl:
    https://raw.githubusercontent.com/openvswitch/ovs/master/
gitdirviewerurl:
    https://github.com/openvswitch/ovs/tree/master/
ovsurl:
    http://openvswitch.org
url:
    https://blp.github.io/ovsweb
